### ISSUE TITLE
Error while running fastq-dump command in Docker image of SRAtoolkit

### ISSUE THREAD

**Issue by ManuelMoradiellos** [pegi3s/dockerfiles#1]
Hi, 
I'm a student new to the world of bioinformatics. Right now I'd doing a small-time internship in which I need to run a series of programs in order to make and analysis of .sra RNAseq data.

While using your sratoolkit image I get the following error:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"fastq-dump\": executable file not found in $PATH": unknown`
I'd tried to look for that executable but I don't find it anywhere inside the docker image

I've double-checked my syntaxis but I still don't get what's not working 
`docker run --rm -v /lmmoradiellos/Datos_RNAseq/RAW:/data pegi3s/sratoolkit fastq-dump /data/'Control Sample_siLuc_1.sra' --outdir /lmmoradiellos/Datos_RNAseq/Fastq`

Maybe I wrote something in a wrong way, but I can't seem to find the mistake.

**Comment by hlfernandez** [comment]
Dear Manuel,

Thank you for reporting this issue, the PATH was updated incorrectly and the `fastq-dump` command was not found. We have just updated the image so that it works properly now, please, try it again. To force Docker to update the image, delete the previous one (`docker rmi pegi3s/sratoolkit`) before running the command again.

Please, note that the `pegi3s/sratoolkit:latest` image contains the 2.9.6 version of sra-tools (it is the same as `pegi3s/sratoolkit:2.9.6`).

With best regards,

          Hugo.

**Comment by ManuelMoradiellos** [comment]
Thanks! Now it's working perfectly.
