### ISSUE TITLE
vcftools cannot Identify the file .vcf 

### ISSUE THREAD

**Issue by tcrispino13** [pegi3s/dockerfiles#7]
Hi, I just want to ask assistance on this problem I keep on experiencing. I've been using the vcftools but it cannot locate the file and cannot determine the file even I am in the right directory and the filename is correct. Thank you so much for your patience!

**Comment by hlfernandez** [comment]
Hi, can you post the command you are executing and the corresponding output?

**Comment by tcrispino13** [comment]
Sure, here it is
![command](https://user-images.githubusercontent.com/78139734/106110586-e0809580-6185-11eb-9533-de8f216a98e7.jpg)

**Comment by hlfernandez** [comment]
Alright, I think that the problem is the `-v` option of the Docker command. You are only specifying the host folder you want to mount, but not the name of such folder in the container, which is indicated after `:`. Thus, you need to write:

`docker run --rm -v C:\Users\tcrispino\Downloads:/data pegi3s/vcftools --vcf /data/final.vcf --extract-FORMAT-info GT`

Note also that the path to the `final.vcf` file must be exist in the container and therefore you should indicate it as `/data/final.vcf`.

**Comment by tcrispino13** [comment]
Thanks! It really works! Thank you so much for your help!

**Comment by hlfernandez** [comment]
Nice, you are welcome!
